In [5]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[2,0],[0,2]])
print("a=")
print(a)
print("b=")
print(b)
u = (a.T)
i = np.eye(2)
print("identity matrix is:")
print(i)
y = np.matmul(a,i)
print(a)
print(3 * a)
print(a + a)
print("the shape of the a is =",a.shape)
o = np.array([[1,2,3],[4,5,6]])
print("the shape of the o matrix is=",o.shape)


a=
[[1 2]
 [3 4]]
b=
[[2 0]
 [0 2]]
identity matrix is:
[[1. 0.]
 [0. 1.]]
[[1 2]
 [3 4]]
[[ 3  6]
 [ 9 12]]
[[2 4]
 [6 8]]
the shape of the a is = (2, 2)
the shape of the o matrix is= (2, 3)
