In [9]:
import numpy as np
X=np.array([1,2,3,4,5])
y=np.array([2,4,5,4,5])

#add a column of ones X
X_b=np.c_[np.ones((len(X),1)),X]
print(X_b)

#normal equation
theta_best=np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
print(theta_best)
y_pred=X_b @ theta_best
print(y)
print(y_pred)

#calculate MSE
mse=np.mean((y - y_pred)**2)
print("MSE:",mse)

alpha=theta_best[0]
beta=theta_best[1]
print("intercept(aplha):",alpha)
print("slope(beta):",beta)



[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]]
[2.2 0.6]
[2 4 5 4 5]
[2.8 3.4 4.  4.6 5.2]
MSE: 0.47999999999999987
intercept(aplha): 2.2000000000000046
slope(beta): 0.6000000000000002
