In [3]:
import numpy as np
from PIL import Image
i = Image.open(r"C:\Users\anjan\ML-Journey\sky_for_ml.jpg").convert("L")
ia = np.array(i)
print("shape:",ia.shape)
print("pixel values:")
print(ia)
print("max pixel value:",ia.max())
print("min pixel value:",ia.min())



shape: (3264, 4928)
pixel values:
[[39 37 36 ... 36 36 35]
 [38 37 36 ... 36 36 35]
 [38 37 36 ... 36 36 35]
 ...
 [ 9 10 11 ... 11 10 10]
 [11 11 13 ... 10 10  9]
 [12 13 15 ... 10 10  9]]
max pixel value: 207
min pixel value: 0
