In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [1]:
import numpy as np

In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy as np

In [4]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from scipy.ndimage import rotate
# 1. Load as NumPy matrix
img = np.array(Image.open("photo.jpg").convert("L")) # grayscale uint8
print("Shape:", img.shape, "| dtype:", img.dtype)
# 2. Brightness via scalar multiply + clip
bright = np.clip(img * 1.5, 0, 255).astype(np.uint8) # +50%
dark = np.clip(img * 0.5, 0, 255).astype(np.uint8) # -50%
# 3. Rotation transformation
rotated = rotate(img, angle=45, reshape=False)
# 4. Side-by-side comparison
fig, axes = plt.subplots(1, 4, figsize=(16, 4))
for ax, im, t in zip(axes,
[img, bright, dark, rotated],
["Original", "+50% Bright", "-50% Dark", "Rotated 45"]):
    ax.imshow(im, cmap="gray")
ax.set_title(t)
ax.axis("off")
plt.tight_layout()
plt.savefig("output.png", dpi=150)
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: 'photo.jpg'

In [5]:
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)
print("shape:",a.shape)


[[1 2]
 [3 4]]
shape: (2, 2)


In [11]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[45,56]])
c = np.matmul(a,b)
print("a mul b is :",c)
d = np.dot(a,b)
print("the dot product of a,b is: ",d)
print(a * 2)
print(b.T)


a mul b is : [[ 91 114]
 [183 230]]
the dot product of a,b is:  [[ 91 114]
 [183 230]]
[[2 4]
 [6 8]]
[[ 1 45]
 [ 2 56]]
